@MatrimonioBackend_HostAddress = https://localhost:44385

GET {{MatrimonioBackend_HostAddress}}/odata/$metadata#Post
Accept: application/json

###
GET {{MatrimonioBackend_HostAddress}}/api/Post
Accept: application/json

###
GET {{MatrimonioBackend_HostAddress}}/odata/Post
Accept: application/json